### ISSUE TITLE
希望能增加ProxmoxVE数据持久化

### ISSUE THREAD

**Issue by xrgzs** [GreenDamTan/DockerFile#1]

**Comment by GreenDamTan** [comment]
惊呆了，居然有人用
有人用的话我看看怎么弄
之前还在想把几个qemu的patch与PVE几个自定义patch合进去的，不过想想看就我自己在用就没管了

**Comment by GreenDamTan** [comment]
env传递密码那个我抄完了
https://github.com/GreenDamTan/DockerFile/commit/751335e4d173ebc0dad7a1a4871d9a27013d528c
密码我拿了这里的作业
https://github.com/jiangcuo/Proxmox-VE-live/blob/main/etc/pvelive/password.sh
至于你说的持久化我没弄懂是哪里的持久化
https://github.com/proxmox/pve-docs/blob/d0cf82da048758025dbd8ec998bd5c28788cbaaa/pmxcfs.adoc#recovery
如果是虚拟机配置的话，映射下就好了，不过记得要保持容器hostname一致
/var/lib/pve-cluster
这个是虚拟机磁盘
/var/lib/vz

有明确需求了再重开这个issues

**Comment by xrgzs** [comment]
持久化就是，给相关文件目录映射出来，使得pve容器删了之后再重新创建能够保留之前在里面的所有数据。

这边测试下来，如果不映射 `/etc/pve` 的话，虚拟机配置不会保留。这些持久化的文件目录，除了 `/var/lib/vz` （存储虚拟磁盘）外，如果首次启用前不将其复制出来，虚拟机开启后pve将无法启动，web ui 无法访问。

也就是说，我认为在 https://github.com/GreenDamTan/DockerFile/blob/dev/ProxmoxVE/deploy.yml 这个文件中，根据这篇文档 https://github.com/proxmox/pve-docs/blob/master/pmxcfs.adoc ，还需加上 `/etc/pve` 这个位置的映射。

只映射 `/var/lib/pve-cluster` 和 `/var/lib/vz` 是不够的。

**Comment by GreenDamTan** [comment]
以前弄那个livePVE的时候，也是映射`/var/lib/pve-cluster`就能持久化虚拟机配置了
之前我们那群里弄Proxmox live也是映射这里处理虚拟机配置持久化的问题
https://github.com/jiangcuo/Proxmox-VE-live/blob/5a7ee983ad288267b13e6e76b55168367f6a7860/scripts/create_rootfs.sh#L142
我个人测试的话，映射`/var/lib/vz`与`/var/lib/pve-cluster`就能保存虚拟机配置与磁盘镜像了
您那边是测试只映射这两个目录不能持久化配置是吗 @xrgzs

**Comment by jjm2473** [comment]
```
/dev/fuse on /etc/pve type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)
```
`/etc/pve`其实是一个fuse挂载的文件系统，也就是pmxcfs，而这个文件系统的数据就存储在`/var/lib/pve-cluster/config.db`里（[文档](https://github.com/proxmox/pve-docs/blob/master/pmxcfs.adoc#recovery)），所以只要持久化`/var/lib/pve-cluster/config.db`就行了。

**Comment by xrgzs** [comment]
我之前应该是卡在某个BUG上了，pmxcfs挂载失败造成服务无法启动，需要给pmxcfs的/etc/pve复制出来挂载。现在暂时没有发现问题。

**Comment by docker-master** [comment]
> 以前弄那个livePVE的时候，也是映射`/var/lib/pve-cluster`就能持久化虚拟机配置了 之前我们那群里弄Proxmox live也是映射这里处理虚拟机配置持久化的问题 https://github.com/jiangcuo/Proxmox-VE-live/blob/5a7ee983ad288267b13e6e76b55168367f6a7860/scripts/create_rootfs.sh#L142 我个人测试的话，映射`/var/lib/vz`与`/var/lib/pve-cluster`就能保存虚拟机配置与磁盘镜像了 您那边是测试只映射这两个目录不能持久化配置是吗 [@xrgzs](https://github.com/xrgzs)

所以可以发一下群吗，习惯进群看看大家怎么弄的，交流一下

**Comment by GreenDamTan** [comment]
> > 以前弄那个livePVE的时候，也是映射`/var/lib/pve-cluster`就能持久化虚拟机配置了 之前我们那群里弄Proxmox live也是映射这里处理虚拟机配置持久化的问题 https://github.com/jiangcuo/Proxmox-VE-live/blob/5a7ee983ad288267b13e6e76b55168367f6a7860/scripts/create_rootfs.sh#L142 我个人测试的话，映射`/var/lib/vz`与`/var/lib/pve-cluster`就能保存虚拟机配置与磁盘镜像了 您那边是测试只映射这两个目录不能持久化配置是吗 [@xrgzs](https://github.com/xrgzs)
> 
> 所以可以发一下群吗，习惯进群看看大家怎么弄的，交流一下

你直接找那个项目的群就好，我自己是没群的，主要是懒
